### ISSUE TITLE
Can you boot your own system without a USB

### ISSUE THREAD

**Issue by cengizhanhakan** [ansonliao/Asrock-B460m-ITX-AC-OC-EFI#11]
I setup my hackintosh using your EFI everything works perfectly. but I cant boot the system without using a usb stick

**Comment by ansonliao** [comment]
Yes, I can, I boot the system without USB normally except debug section.

**Comment by cengizhanhakan** [comment]
I mounted my EFI folder after installation. But bios just skips opencore and boots into windows

**Comment by ansonliao** [comment]
@cengizhanhakan 
mounted the EFI sector of the HDD/SSD, and copy the EFI directory of USB to the EFI sector of the HDD/SSD.
Apology for no experience on the multiple-OSs boot (for example, Mac and Windows, or Mac and Ubuntu), maybe you can do some investigation from Google.

**Comment by cengizhanhakan** [comment]
So that just made me think that maybe I didnt mount properly.
-I used mountefi and selwcted my usb then my ssd
-I moved usb files to volumes/efi

**Comment by ansonliao** [comment]
@cengizhanhakan 
I think multi OSs boot maybe not only copy the EFI to the SSD/HDD of Hackintosh, and I read some post before, multiple OSs boot in: 
1. Multiple OSs installed in 1-SSD/HDD
2. Multiple OSs installed in different SSD/HDD (for example, hackintosh installed in SSD1, Windows 10 installed in SSD2)

these two installation of multiple OSs, the booting looks like has the different solution.

But I also suggest you do some investigation about multiple OSs booting solution from Google or hackintosh forums, for example: https://hackintosher.com/guides/hackintosh-dual-boot-windows-10-and-macos-high-sierra/

**Comment by cengizhanhakan** [comment]
It turned out to be an M2 problem. 
My windows is in NVMe and MacOS is in SATA Drive. When you install windows after you install Catalina, It overrides your EFI folder and replaces BOOTX64.efi. 
Thanks.

**Comment by ansonliao** [comment]
@cengizhanhakan 
That what I said that multiple OSs boot setting is not only copy and paste the `EFI` directory to the target SSD/HDD.
