### ISSUE TITLE
Pardon?Could u plz tell me how to put BCM94360CS2 into that case？

### ISSUE THREAD

**Issue by menghanjun001** [ansonliao/Asrock-B460m-ITX-AC-OC-EFI#12]
I heard that inwin chopin case could not support PCIE,so I hesitate whether to purchase that blue tooth model!

**Comment by ansonliao** [comment]
@menghanjun001 
please check this link, check the header image.
https://icyleaf.com/2019/03/asrock-z390-gaming-itx-install-hackintosh-tutorial/

**Comment by ansonliao** [comment]
@menghanjun001 
or you can buy this one, I using this one.
Search the keyword in TaoBao: `浩霖 M.2 key 转接卡 延长线`

![image](https://user-images.githubusercontent.com/6060224/98369661-2f100f00-2031-11eb-929b-f0b4fee8a02d.png)

**Comment by ansonliao** [comment]
No update from @menghanjun001 , close this issue.
