### ISSUE TITLE
睡眠唤醒后显示器依旧黑屏

### ISSUE THREAD

**Issue by wumilun** [ansonliao/Asrock-B460m-ITX-AC-OC-EFI#14]
首先感谢作者，您的EFI在华擎H410itx/ac上工作基本完美，但存在和iGPU Patching所说的一样的问题。
配置为：10500ES（QSRK），32G，华擎H410itx/ac，无独显，主板DP接口连接显示器。
根据华擎官方回答，H410和B460这两款ITX除了在BIOS和散热上有所不同，其余都是相同的，我尝试了定制USB，igfxonln=1等操作，问题依旧，求教作者这个应该如何解决？

**Comment by ansonliao** [comment]
@wumilun 
请问你的hackintool下面的video connectors是什么内容？
![image](https://user-images.githubusercontent.com/6060224/101129194-1b5dc580-363c-11eb-9cd4-45ceb522d768.png)


还有你的iGPU patching内容是什么？

**Comment by wumilun** [comment]
麻烦您看下
<img width="656" alt="1" src="https://user-images.githubusercontent.com/60733391/101135402-b6f43380-3646-11eb-8d43-0d0bb182d3a3.png">

**Comment by wumilun** [comment]
<img width="845" alt="WX20201204-155328@2x" src="https://user-images.githubusercontent.com/60733391/101136960-08052700-3649-11eb-9ae1-e3dded75976a.png">

**Comment by ansonliao** [comment]
@wumilun 
HDMI和DP是分别是哪一个接口？
![](https://user-images.githubusercontent.com/6060224/101129194-1b5dc580-363c-11eb-9cd4-45ceb522d768.png)

**Comment by ansonliao** [comment]
@wumilun 
Please refer to the official document: https://dortania.github.io/OpenCore-Post-Install/gpu-patching/intel-patching/

**Comment by wumilun** [comment]
经过尝试，把型号从iMac19,1改成macmini8,1这个情况就不存在了，再次谢谢您的回复～

**Comment by ansonliao** [comment]
@wumilun 
你的独显么?

**Comment by wumilun** [comment]
核显

**Comment by ansonliao** [comment]
哦，一般来说核显选macmini机型。
不过能解决你的问题就好。
在macmini下，在正确确定每个视频输出端口的情况下，可以试试[one-key-hidpi](https://github.com/xzhih/one-key-hidpi)
