### ISSUE TITLE
感谢作者，有个问题：使用此引导，不能关机

### ISSUE THREAD

**Issue by drowning** [ansonliao/Asrock-B460m-ITX-AC-OC-EFI#16]
OS: macOS Catalina 10.15.7 19H114 x86_64 
Host: Hackintosh (SMBIOS: Macmini8,1) 
Kernel: 19.6.0 
Uptime: 3 mins 
Packages: 166 (brew) 
Shell: zsh 5.7.1 
Resolution: 2560x1440 
DE: Aqua 
WM: Quartz Compositor 
WM Theme: Blue (Dark) 
Terminal: HyperTerm 
Terminal Font: Menlo 
CPU: Intel i5-10500 (12) @ 3.10GHz 
GPU: Intel UHD Graphics 630 
Memory: 8992MiB / 65536MiB 

操作关机后，系统会关闭，硬盘灯会灭，电源灯长亮，主板供电未关闭

**Comment by ansonliao** [comment]
主板是什么？

**Comment by drowning** [comment]
> 主板是什么？
主板：Asrock-B460m-ITX

**Comment by ansonliao** [comment]
可能是 `SSDT-PLUG.aml` ， `SSDT-AWAC.aml` 等这几个和你的CPU不匹配，试试按照OpenCore官方的教程重新做：
[https://dortania.github.io/Getting-Started-With-ACPI/ssdt-platform.html#desktop](https://dortania.github.io/Getting-Started-With-ACPI/ssdt-platform.html#desktop)
- [Fixing Power Management (SSDT-PLUG)](https://dortania.github.io/Getting-Started-With-ACPI/Universal/plug.html)
- [Fixing System Clocks (SSDT-AWAC/RTC0)](https://dortania.github.io/Getting-Started-With-ACPI/Universal/awac.html)
- [https://dortania.github.io/Getting-Started-With-ACPI/Universal/rhub.html](https://dortania.github.io/Getting-Started-With-ACPI/Universal/rhub.html)
- [Fixing Embedded Controller (SSDT-EC/USBX)](https://dortania.github.io/Getting-Started-With-ACPI/Universal/ec-fix.html)

获取DSDT：
- https://dortania.github.io/Getting-Started-With-ACPI/Manual/dump.html#getting-a-copy-of-our-dsdt

也可以偷偷懒，根据你DSDT的具体情况去黑果小兵那去下载相对应的 `aml` 文件： https://github.com/daliansky/OC-little

**Comment by ansonliao** [comment]
@drowning 
你不打算更新一下？
