### ISSUE TITLE
请问有掉帧现象出现吗

### ISSUE THREAD

**Issue by Umenezumi** [ansonliao/Asrock-B460m-ITX-AC-OC-EFI#18]
HD 630 ，4k 显示器，肉眼可见的掉帧

**Comment by ansonliao** [comment]
Intel I5 10500 ES (QSRK) 的GPU不太理想，玩swift的playground特别明显。
我手上有i5 9600K，之前使HD630使用过大概半年，感觉家用使用问题不大。

**Comment by Umenezumi** [comment]
> Intel I5 10500 ES (QSRK) 的GPU不太理想，玩swift的playground特别明显。
> 我手上有i5 9600K，之前使HD630使用过大概半年，感觉家用使用问题不大。

加装免驱卡蓝宝石 R9 380 后解决该问题，应该是核显性能较差的原因

**Comment by ansonliao** [comment]
是的，10500 es 核显性能不怎么样
