### ISSUE TITLE
有关开机第一阶段logo变大的解决方法

### ISSUE THREAD

**Issue by MyheadveryFe** [ansonliao/Asrock-B460m-ITX-AC-OC-EFI#2]
首先非常感谢你，这个efi省去我很多时间在配置上。
logo变大的解决方法：在NVRAM设置中将UUID为4D1EDE05开头的项，键为UIScale的值修改为01即可，已经测试成功

**Comment by ansonliao** [comment]
这个是可以的，不过只能改第一阶段logo的大小，不能改第二阶段的大小。
因为我的显示器是4K，所以我喜欢大logo，所以我是想，两个阶段都是大logo，这个现在似乎还无解

**Comment by ansonliao** [comment]
@MyheadveryFe 
如果想要两个阶段的logo都是大logo，其实是有解决方案的，如果有独显的话，第二阶段的logo应该是大logo，这样两个阶段的logo都是大logo

**Comment by MyheadveryFe** [comment]
> @MyheadveryFe
> 如果想要两个阶段的logo都是大logo，其实是有解决方案的，如果有独显的话，第二阶段的logo应该是大logo，这样两个阶段的logo都是大logo

我猜使用hidpi可能可行。我记得修改hidpi第一次开机logo会巨大。之后又正常。也许里面有些门道?

**Comment by ansonliao** [comment]
@MyheadveryFe 
改变第一次logo的大小，改UIScale就行了。
正如我说的，我是想控制开机第二阶段的logo的大小。
`one-key-hidpi` 我也用过，不过在我的机器上对控制开机第二阶段logo的大小是没什么效果。

**Comment by ansonliao** [comment]
Closed this issue as no updates from @MyheadveryFe
