### ISSUE TITLE
请问使用的免驱卡 CS2 是插在那个接口的？

### ISSUE THREAD

**Issue by Umenezumi** [ansonliao/Asrock-B460m-ITX-AC-OC-EFI#20]
是通过拆除屏蔽罩添加转接卡插在 wifi 位吗？

**Comment by ansonliao** [comment]
是的

**Comment by Umenezumi** [comment]
> 是的, 可以看看这个大佬的图片：[点这里](https://icyleaf.com/2019/03/asrock-z390-gaming-itx-install-hackintosh-tutorial/)
感谢分享
