### ISSUE TITLE
bios要怎么设置？

### ISSUE THREAD

**Issue by qq27375** [ansonliao/Asrock-B460m-ITX-AC-OC-EFI#21]
下载了 设置了三码，但是进不了引导界面。
网卡是dw1560

**Comment by wraptor** [comment]
+1，bios需要改动吗，我现在的参照另一位的EFI改的
[https://github.com/WenvyG/ASRock-B460M-ITX-ac-Hackintosh](https://github.com/WenvyG/ASRock-B460M-ITX-ac-Hackintosh)
```
安装前准备
开机按F2或Del进入BIOS

Disabled:

Secure Boot

CSM

CFGLock

VT-d

Enable:

XHCI Hand Off

Above 4GB Decoding

F10 保存设置并重启
```

现在他没维护了，我换成你的EFI进不去

**Comment by ansonliao** [comment]
BIOS设置和 @wraptor 列得差不多。
至于为什么进不了引导界面，得看看具体的硬件配置和BIOS设置

**Comment by wraptor** [comment]
> BIOS设置和 @wraptor 列得差不多。
> 至于为什么进不了引导界面，得看看具体的硬件配置和BIOS设置

我的BIOS设置就是如上列的那样，硬件的话板子一样，cpu是10400，网卡是1820A

**Comment by ansonliao** [comment]
@wraptor 
CPU不一样，请定制ACPI，我在README.MD写明了我的CPU是10500es，EFI只对10500es有效，其它的就看运气

**Comment by ansonliao** [comment]
@qq27375 请问你的具体问题是什么？
3天内没回复会关闭issue的。
