### ISSUE TITLE
After OC upgraded, the OC version keep old version number

### ISSUE THREAD

**Issue by ansonliao** [ansonliao/Asrock-B460m-ITX-AC-OC-EFI#23]
Updated the OC core files to the latest version, when running the OC version display command-line:
```shell
nvram 4D1FDA02-38C7-4A6A-9CC6-4BCCA8B30102:opencore-version
```
the OC version is not the latest version number.

Need to fix.

**Comment by Umenezumi** [comment]
请问有执行 clean nvram 操作吗？

**Comment by ansonliao** [comment]
@Umenezumi 
执行了

**Comment by ansonliao** [comment]
Please check the release:
https://github.com/ansonliao/Asrock-B460m-ITX-AC-OC-EFI/releases/tag/2.3

**Comment by ShiYuechao** [comment]
这个OC版本提示0.6.6升级0.7.3的问题，怎么解决啊？

**Comment by ShiYuechao** [comment]
我的USB上面的2个接口不能使用，插上没反应
The two interfaces on my USB can't be used. There's no response when plugged in.

**Comment by ansonliao** [comment]
What's your motherboard, CPU, and GPU?
