### ISSUE TITLE
Asrock B460m-ITX/AC 只有一个M2接口

### ISSUE THREAD

**Issue by benlin4425** [ansonliao/Asrock-B460m-ITX-AC-OC-EFI#25]
Asrock B460m-ITX/AC 只有一个M2接口，BCM94360CS2和Intel 760P 512 GB怎么装？

**Comment by ansonliao** [comment]
BCM94360CS2接在主板WiFi槽上，SSD接在M2上

**Comment by benlin4425** [comment]
> BCM94360CS2接在主板WiFi槽上，SSD接在M2上

谢谢您的解答
