### ISSUE TITLE
求更新啊～～

### ISSUE THREAD

**Issue by wumilun** [ansonliao/Asrock-B460m-ITX-AC-OC-EFI#27]
按照过去的方法升级OC后无法开机了，求大大更新哇～

**Comment by ansonliao** [comment]
Please check branch https://github.com/ansonliao/Asrock-B460m-ITX-AC-OC-EFI/tree/issue-23_fix_the_oc_version_incorrect

**Comment by ansonliao** [comment]
Please check the release:
https://github.com/ansonliao/Asrock-B460m-ITX-AC-OC-EFI/releases/tag/2.3
