### ISSUE TITLE
Airpods pro works at 8khz

### ISSUE THREAD

**Issue by bwelco** [ansonliao/Asrock-B460m-ITX-AC-OC-EFI#3]
Thanks for your OC Configuration.

I got an issue that my airpods pro only works at 8khz (input source), but it works well on my MacBook Pro 16'

Same issue here: https://www.tonymacx86.com/threads/hackintosh-airpods-sound-quality-issue.296596/

My wifi & bluetooth model is BCM94360CS2
![image](https://user-images.githubusercontent.com/9380897/93732101-6140eb00-fc02-11ea-8bec-e8208e5fb3ff.png)

Here is my MIDI setup screenshot
![image](https://user-images.githubusercontent.com/9380897/93732116-73bb2480-fc02-11ea-913a-b1754a1fe669.png)

**Comment by ansonliao** [comment]
@bwelco 
Apology for this as I no AirPods devices, no idea how to debug and fixed it

**Comment by ansonliao** [comment]
no feedback from the reporter, close this issue.
