### ISSUE TITLE
SMBIOS

### ISSUE THREAD

**Issue by mreser99** [ansonliao/Asrock-B460m-ITX-AC-OC-EFI#32]
Hi, thank you for your work. I'm wondering which smbios are you using and how did you manage iservices fix?

**Comment by ansonliao** [comment]
1. You can check the `config.plist`, the `smbios` default as `Macmini8,1` because I no GPU card.
2. For iServices issue, you can reference: https://dortania.github.io/OpenCore-Post-Install/universal/iservices.html
