### ISSUE TITLE
some problem bother me 

### ISSUE THREAD

**Issue by wangzai2ni** [ansonliao/Asrock-B460m-ITX-AC-OC-EFI#33]
hi bro.my pc is most the same as yours.
but i still use Intel WiFi/Bluetooth Module , the wifi problem is fix, but the bluetooth dosen't work 
and the big apple logo time is too long ..
i don't know how to fix these problem

**Comment by ansonliao** [comment]
1. For the WiFi/Bth, I suggest you replace the intel module with the Broadcom WiFi/Bth module
2. For the big apple long loading issue, you can enable the verbose mode to check which step is take the long time, then search them by Google

**Comment by wangzai2ni** [comment]
好吧。。。。

**Comment by wangzai2ni** [comment]
主要我对隔空投送没用  我不用苹果手机   所以不想换黑果卡。。。。。
大哥有时间  搞一个呗

**Comment by ansonliao** [comment]
I suggest you read [itlwm](https://github.com/OpenIntelWireless/itlwm) in detail and carefully if you don't want to replace the intel wireless card with the Broadcom wireless card, communicate the authors of `itlwm` when you meet the problems.
