### ISSUE TITLE
Monterey 12.0.1 Bluetooth not work

### ISSUE THREAD

**Issue by johnyang007** [ansonliao/Asrock-B460m-ITX-AC-OC-EFI#34]
hi， bro
i had installed monterey 12.0.1 on my PC which same as your hardware configuration.  wireless card is BCM94360cs2. 
now i catch out the bluetooth not work. in OS can find & connect the trackpad, but trackpad not move, not touch, not click.

and in hackintools soft the bluetooth not loaded.  how can i fix the problem?

**Comment by SergeiAlekseenko** [comment]
Hi,

I had installed Monterey 12.0.1 but I had to get back to Big Sur because in
Monterey my Radeon RX570 graphic card worked in 30Hz mode (no drivers as I
understand).
I ordered a Wifi-Bluetooth card (7265NGW, M.2 NGFF WiFi (b/g/n/ac),
2.4/5Ghz, Bluetooth 4.0, Intel) and I will try to set it up next week.

Best Regards,
Sergei Alekseenko


чт, 18 нояб. 2021 г. в 04:02, ken ***@***.***>:

**Comment by ansonliao** [comment]
Hi @johnyang007 , 
My wireless card is `BCM94360CS2` as well, after being upgraded to Monteray 12.0.1, I didn't meet any problems with the wireless card.
I suggest can raise your problem in the professional Hackintosh forum, such as [TonyMacX86](https://www.tonymacx86.com/forums/monterey-desktop-support.209/)

**Comment by ansonliao** [comment]
Hi @SergeiAlekseenko ,
Did you try the resolution and refresh Hz configuration tool: [EasyRes](http://easyresapp.com/)?
I suggest it's worth to have a try.

**Comment by ansonliao** [comment]
Hi @johnyang007 ,
Did you check your adaptor of the wireless whether works fine when its Bluetooth function is out of work?
Before I also meet this problem, we have to make sure the insulation for the contacts between the adaptor and the wireless card, similar to below, the adaptor is cheap and easy to be destroyed by the electrostatic then the adaptor will be damaged.

![image](https://user-images.githubusercontent.com/6060224/142426775-f03b82de-b76a-491f-b5de-eeac3f695060.png)

**Comment by johnyang007** [comment]
> Hi @johnyang007 , Did you check your adaptor of the wireless whether works fine when its Bluetooth module is out of work? Before I met this problem as well, we have to make sure the insulation for the contacts between the adaptor and the wireless card, similar to below, the adaptor is cheap and easy to be destroyed by the electrostatic then the adaptor will be damaged.
> 
> ![image](https://user-images.githubusercontent.com/6060224/142426775-f03b82de-b76a-491f-b5de-eeac3f695060.png)

i am reinstall BigSur last night. now the BT work very well. So i think some BT driver mistake happened in Monterey。
i’ll upgrade to Monterey a few weeks later.

**Comment by johnyang007** [comment]
BTW, the wireless card with adaptor isolution i had deal

**Comment by wxxsfxyzm** [comment]
> Hi @johnyang007 ,
> My wireless card is `BCM94360CS2` as well, after being upgraded to Monteray 12.0.1, I didn't meet any problems with the wireless card.
> I suggest can raise your problem in the professional Hackintosh forum, such as [TonyMacX86](https://www.tonymacx86.com/forums/monterey-desktop-support.209/)

No Problem at all after wake from sleep ??

**Comment by johnyang007** [comment]
i change SMBIOS from Mac mini to iMac20,1 because iMac configuration has high performance. 

the iGPU connector mapping was not same as Mac mini. so after sleep can wakeup good but the Monitor won't display which connect by DP. 

hackintools capture img:
![image](https://user-images.githubusercontent.com/6967863/144209393-0973846a-5fd2-43b8-b20b-4cdfe81a6f29.png)

is am i need remapping the connector configuration? or buy a  dGPU?

**Comment by ansonliao** [comment]
@johnyang007 
Maybe you can try to map the correct monitor output port type:
https://dortania.github.io/OpenCore-Post-Install/gpu-patching/#intel-igpu-patching
