### ISSUE TITLE
disk hash mismatch

### ISSUE THREAD

**Issue by wwbingo** [ansonliao/Asrock-B460m-ITX-AC-OC-EFI#35]
after upgrade to macos 12,  something wrong may happend when system up,  I need to restart the system.
do you known what happen

system log :
[ 1092.855202]: sendIONotification:2211: Sending notification about e0084009 for APFS snapshot 1.10
[ 1092.855219]: sendIONotification:2217: Sending additional notification about e0084009 for the parent of APFS snapshot 1.10
[ 1092.855244]: apfs_announce_hash_mismatch:14635: disk1s5 Data hash mismatch for 16384 bytes at offset 114409472 in compressed data stream 1152921500312751677 of inode 1152921500312751676: expected 83cfcc0756222cc577f6d1193019e4781d6d7f2da3a3ac0ea0ca777f2e154eeb, got 347d9270b1337e1cd43e90afcbc0639c2be26c9fc973bfe2beb25b1a2a348bf4
[ 1092.855282]: decmpfs.c:1573:decmpfs_pagein_compressed: <private>: Verification failed with error 94, uplPos = 114409472, uplSize = 16384, did_read = 16384, valid_pages = 3, invalid_pages = 1, tail_page_valid = 1
[ 1092.855293]: decmpfs.c:1615:decmpfs_pagein_compressed: <private>: err 94
[ 1092.855314]: IOReturn CoreAnalyticsUserClient::sendDataToUser(uint8_t *, size_t)::289: sending 819 bytes

**Comment by ansonliao** [comment]
Hi @wwbingo , I never meet your problem, maybe you can ask help from [TonyMacx86](https://www.tonymacx86.com/)
