### ISSUE TITLE
efi遇到的部分问题

### ISSUE THREAD

**Issue by chengyinghaoswat** [ansonliao/Asrock-B460m-ITX-AC-OC-EFI#36]
楼主的efi引导安装使用都没有太大的问题
就是系统刚启动的时候电脑会很卡
在苹果系统中，鼠标的拖移都会出现明显的卡顿
但是过几秒钟就好了，不知道是为何
我使用的是dp接口

**Comment by ansonliao** [comment]
Please list down the hardware spec.

**Comment by johnyang007** [comment]
> Please list down the hardware specifications.

is https://github.com/ansonliao/Asrock-B460m-ITX-AC-OC-EFI/releases/tag/2.4.1 support Monterey 12.1 ?

**Comment by ansonliao** [comment]
@johnyang007 
My machine now is running Monterey 12.1 with version [2.4.1](https://github.com/ansonliao/Asrock-B460m-ITX-AC-OC-EFI/releases/tag/2.4.1)
