### ISSUE TITLE
你们有系统内关机，主板不断电，风扇继续转的问题吗？

### ISSUE THREAD

**Issue by fengcms** [ansonliao/Asrock-B460m-ITX-AC-OC-EFI#4]
你们有系统内关机，主板不断电，风扇继续转的问题吗？

其他一切正常，现在就这一个问题。我现在是关机后，把电源-_-|||，或者干脆不关机，等睡眠后，风扇停转。。。。

**Comment by ansonliao** [comment]
@fengcms 
No power off issue, suggest you to check your `SSDT-PLUG.aml`, `SSDT-EC.aml/SSDT-USBX.aml`, `SSDT-AWAC.aml/SSDT-RTC0.aml`, etc. are created by following [the official guideline of OpenCore](https://dortania.github.io/Getting-Started-With-ACPI/), also suggest check the USB-mapping.

**Comment by ansonliao** [comment]
@fengcms 
BTW, please describe your issue clear, for example `把电源-_-|||，` of `把电源-_-|||，或者干脆不关机`, what it means of your operation?

**Comment by ansonliao** [comment]
no feedback from the reporter, close this issue.

**Comment by yuraph** [comment]
我也遇到同样的问题，问题点是开启了主板上的蓝牙(bcm94352z)，关闭的情况下就风扇就不会继续转。
