### ISSUE TITLE
HDMI display occasionally go black under dual monitors

### ISSUE THREAD

**Issue by ztmo520** [ansonliao/Asrock-B460m-ITX-AC-OC-EFI#47]
When using dual displays, the HDMI display will appear with stripes on the login screen. It will return to normal after a few seconds. Besides, the HDMI monitor will occasionally go black for several seconds during use and then return to normal. I made some modifications to fix this problem.

1. Change platform information to 'iMac20, 1'. This seems to support the 10th generation CPU better.
2. Modify framebuffer patching. Remove device-id, It can be natively supported on 10.15 and above. Only the HDMI interface is modified, and other buffer frames remain the default. Removed con1 and con2 modification.

AAPL,ig-platform-id: 07009B3E
framebuffer-con0-enable: 01000000
framebuffer-con0-type: 00080000
framebuffer-patch-enable: 01000000

After I did this, the problem disappeared. But I don't know if this will bring other problems in other aspects, such as sleep. I really appreciate your work.

**Comment by ansonliao** [comment]
Thanks for your sharing @ztmo520 , as no dual display is required, so I didn't try this configuration before, I think depending on your actual demands, configure the framebuffer correctly, should be met your goals.
