### ISSUE TITLE
System crashed after deep sleep

### ISSUE THREAD

**Issue by bwelco** [ansonliao/Asrock-B460m-ITX-AC-OC-EFI#5]
Every time my pc sleep for 10+ hours, it MUST crash after wakeup.

Here is my log. What should I do to solve this issue?

![image](https://user-images.githubusercontent.com/9380897/94094345-d5bd9900-fe51-11ea-83f7-cde1c970b1cb.png)

Another question: Should I apply the iGPU patching? Is it MUST or optional?

I am using an RX580 graphics card

**Comment by ansonliao** [comment]
@bwelco 
1. 
Apology for no experience on long hours sleep, for my this hackintosh, sleep about 3-4 hours is no system crash issue not.
If you are looking for the long hours sleep, maybe @fzlee can help you: https://github.com/fzlee/B460M-ITX-AC-EFI

Also I would like to share that sleep issue mainly cause the by SSDTs and USB mapping, please make sure you created the correct SSDT aml files depends on your hardwares and following the guideline of OpenCore, and map the USB ports correctly.
Also if can't solve your problem, I recommend you to ask help from the forums of Hackintosh better, such as `tonymacx86`.

2. 
I have another Hackintosh with dGPU RX 5500 XT, with CPU i5 9600K, in this machine, I didn't patching the iGPU, and no problem so far.

**Comment by ansonliao** [comment]
@bwelco 
Please comment any solution you did.
