### ISSUE TITLE
4k卡顿

### ISSUE THREAD

**Issue by tonglei1989** [ansonliao/Asrock-B460m-ITX-AC-OC-EFI#54]
首先感谢分享！我直接用了你的efi，我的硬件除了cpu是10400以外，其他和你的配置都相同。4k分辨率（dp连接）开启hidpi时，使用一段时间后图形界面就会有明显的卡顿感，gpu监控历史显示gpu使用率时不时会飙升到100%，但是cpu和内存的使用率并不高，请教可能是什么原因。

**Comment by ansonliao** [comment]
@tonglei1989 
最好重新做APCI，因为CPU不一样。

**Comment by tonglei1989** [comment]
> 

已经解决了，添加引导参数igfxrpsc=1就可以了
