### ISSUE TITLE
请问显卡换成蓝宝石rx460 4g超白金的话可直接用您的efi吗？

### ISSUE THREAD

**Issue by chendi2** [ansonliao/Asrock-B460m-ITX-AC-OC-EFI#58]
如题，我的配置单是：
CPU：i5 10500 es QSRK 500
主板：B460 itx 500
网卡：bcm94352z 0
显卡：蓝宝石 RX460 4GB 超白金版 400
散热器：利民（Thermalright） AK120 CPU散热器 150
固态：爱国者P7000Z 2T 500
sata盘：三星860 evo 0
电源：微星(MSI) MAG A650BN 300
机箱：傻瓜超人k88 150

**Comment by ansonliao** [comment]
可以试试，不过我没有独立显卡的配置

**Comment by chendi2** [comment]
免驱的话按理说没问题

**Comment by ansonliao** [comment]
独立显卡要改点东西的，BIOS也要改点设置

**Comment by chendi2** [comment]
> 独立显卡要改点东西的，BIOS也要改点设置

好的，我看到国光有个帖子介绍这个情况，我先试试
