### ISSUE TITLE
Some items in "/kernel/add/" of 'config_itlwm.plist' need to be fixed

### ISSUE THREAD

**Issue by Caoyvming** [ansonliao/Asrock-B460m-ITX-AC-OC-EFI#7]
You said you have “Removed fake PCI ID kexts that sovled audio device before: `FakePCIID_Intel_HDMI_Audio.kext`, `FakePCIID.kext`” in Changelog, and yes, the two files have disapeared. BUT! You did not update the config_itlwm.plist! This will make OpenCore cant load correctly! So please fixed it as quickly as possible

**Comment by ansonliao** [comment]
There no plan to support to keep the config_itwlm.plist up to date, normally if you want to running intel wifi module with your hackintosh, the step is simply: 

only download the Intel WiFi KEXTs from the site, and then add the KEXTs to your `config.plist`, and then install `HeliPort` in your Hackintosh, then restart. 


I suggest you check the documents from the repo of itwlm or join its Gitter channel. 
I don't provide any support of the intel wifi support.

**Comment by Caoyvming** [comment]
Okey, thanks.





------------------ Original ------------------
