### ISSUE TITLE
bcm94352z无线网卡蓝牙开启的状态下，关闭风扇一直转

### ISSUE THREAD

**Issue by yuraph** [ansonliao/Asrock-B460m-ITX-AC-OC-EFI#8]
首先感谢作者的efi，我网卡使用的bcm94352z免驱，由于使用的蓝牙键盘和鼠标，蓝牙一直开启，关机的情况下风扇一直转，但是屏幕无输出。 关闭蓝牙，然后再关机，风扇才会停，不知道有没有遇到同样的问题。

**Comment by ansonliao** [comment]
@yuraph 
可以看看这位朋友的repo，他的免驱卡和你的一样： https://github.com/fzlee/B460M-ITX-AC-EFI

另外，我之前也碰到过重启、关机变重启的问题，一般来说这些问题是由不正确的ACPI引起的，特别是关于CPU在SSDT，还有是定制USB。
从你说的情况来看，可以认真查看一下ACPI是否完全官方的教程来做的，先确定ACPI是没问题的，再看看USB定制。

**Comment by yuraph** [comment]
谢谢回答，我再尝试一下。 今天的问题，我再次仔细测试了一下，是蓝牙打开，并且连接了设备(蓝牙鼠标、蓝牙键盘等)的情况下，关机风扇会一直转。

**Comment by ansonliao** [comment]
我有两张免驱卡：BCM94360CS2和BCM943602CD，我用的是Magic Keyboard 2蓝牙键盘和Logitech Master 3蓝牙鼠标，没有任何问题

**Comment by yuraph** [comment]
@ansonliao  再反馈个现象，每次开机进入黑苹果系统，都有大约10-20s的小卡顿，现象是，鼠标拖动比正常时候慢，你们有这样的问题吗？

**Comment by ansonliao** [comment]
@yuraph 有碰到过，不过不是每次开机都这样
