### ISSUE TITLE
10500的cpu可以用吗

### ISSUE THREAD

**Issue by aanq** [ansonliao/Asrock-B460m-ITX-AC-OC-EFI#9]

**Comment by yuraph** [comment]
10500 cpu可以使用，我的电脑就是B460M  ITX + 10500

**Comment by aanq** [comment]
@yuraph 好的，谢谢，请问下 dw1560 尺寸是不是和这个主板的原装网卡一样大小，可以完美替换？

**Comment by yuraph** [comment]
@aanq  我用的 BCM94352z，这款可以尺寸上可以完美替换。 你说的这款不知道

**Comment by aanq** [comment]
@yuraph 谢谢，我最后也买了这个型号的

**Comment by ansonliao** [comment]
ROG主板或华硕WiFi Go的WiFi模块BCM94360H MB了解下

**Comment by ansonliao** [comment]
94352z的价钱真下不了手
